import { Product, Banner, Country } from './types';

export const COUNTRIES: Country[] = [
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', symbol: '£', phonePrefix: '+44', phoneLength: 10, postcodeRegex: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i, shippingFee: 1.50, conversionRate: 1 },
  { name: 'India', code: 'IN', currency: 'INR', symbol: '₹', phonePrefix: '+91', phoneLength: 10, postcodeRegex: /^\d{6}$/, shippingFee: 3.00, conversionRate: 110.45 },
  { name: 'United States', code: 'US', currency: 'USD', symbol: '$', phonePrefix: '+1', phoneLength: 10, postcodeRegex: /^\d{5}(-\d{4})?$/, shippingFee: 3.00, conversionRate: 1.26 },
  { name: 'Germany', code: 'DE', currency: 'EUR', symbol: '€', phonePrefix: '+49', phoneLength: 11, postcodeRegex: /^\d{5}$/, shippingFee: 3.00, conversionRate: 1.18 },
  { name: 'Canada', code: 'CA', currency: 'CAD', symbol: 'C$', phonePrefix: '+1', phoneLength: 10, postcodeRegex: /^[A-Z]\d[A-Z] ?\d[A-Z]\d$/i, shippingFee: 3.00, conversionRate: 1.72 },
  { name: 'Australia', code: 'AU', currency: 'AUD', symbol: 'A$', phonePrefix: '+61', phoneLength: 9, postcodeRegex: /^\d{4}$/, shippingFee: 3.00, conversionRate: 1.91 },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', symbol: 'DH', phonePrefix: '+971', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 3.00, conversionRate: 4.63 },
  // Adding the rest of the 193 countries (Comprehensive List)
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', symbol: 'Af', phonePrefix: '+93', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 90 },
  { name: 'Albania', code: 'AL', currency: 'ALL', symbol: 'L', phonePrefix: '+355', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 110 },
  { name: 'Algeria', code: 'DZ', currency: 'DZD', symbol: 'DA', phonePrefix: '+213', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 150 },
  { name: 'Andorra', code: 'AD', currency: 'EUR', symbol: '€', phonePrefix: '+376', phoneLength: 6, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Angola', code: 'AO', currency: 'AOA', symbol: 'Kz', phonePrefix: '+244', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 600 },
  { name: 'Antigua and Barbuda', code: 'AG', currency: 'XCD', symbol: '$', phonePrefix: '+1-268', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Argentina', code: 'AR', currency: 'ARS', symbol: '$', phonePrefix: '+54', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 450 },
  { name: 'Armenia', code: 'AM', currency: 'AMD', symbol: '֏', phonePrefix: '+374', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 480 },
  { name: 'Austria', code: 'AT', currency: 'EUR', symbol: '€', phonePrefix: '+43', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Azerbaijan', code: 'AZ', currency: 'AZN', symbol: '₼', phonePrefix: '+994', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.1 },
  { name: 'Bahamas', code: 'BS', currency: 'BSD', symbol: '$', phonePrefix: '+1-242', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Bahrain', code: 'BH', currency: 'BHD', symbol: '.د.ب', phonePrefix: '+973', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 0.47 },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', symbol: '৳', phonePrefix: '+880', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 130 },
  { name: 'Barbados', code: 'BB', currency: 'BBD', symbol: '$', phonePrefix: '+1-246', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.5 },
  { name: 'Belarus', code: 'BY', currency: 'BYN', symbol: 'Br', phonePrefix: '+375', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.2 },
  { name: 'Belgium', code: 'BE', currency: 'EUR', symbol: '€', phonePrefix: '+32', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Belize', code: 'BZ', currency: 'BZD', symbol: '$', phonePrefix: '+501', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.5 },
  { name: 'Benin', code: 'BJ', currency: 'XOF', symbol: 'Fr', phonePrefix: '+229', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Bhutan', code: 'BT', currency: 'BTN', symbol: 'Nu.', phonePrefix: '+975', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 100 },
  { name: 'Bolivia', code: 'BO', currency: 'BOB', symbol: 'Bs.', phonePrefix: '+591', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 8.7 },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: 'BAM', symbol: 'KM', phonePrefix: '+387', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.3 },
  { name: 'Botswana', code: 'BW', currency: 'BWP', symbol: 'P', phonePrefix: '+267', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 16 },
  { name: 'Brazil', code: 'BR', currency: 'BRL', symbol: 'R$', phonePrefix: '+55', phoneLength: 11, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 6.2 },
  { name: 'Brunei', code: 'BN', currency: 'BND', symbol: '$', phonePrefix: '+673', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.7 },
  { name: 'Bulgaria', code: 'BG', currency: 'BGN', symbol: 'лв', phonePrefix: '+359', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.3 },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', symbol: 'Fr', phonePrefix: '+226', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Burundi', code: 'BI', currency: 'BIF', symbol: 'Fr', phonePrefix: '+257', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3500 },
  { name: 'Cabo Verde', code: 'CV', currency: 'CVE', symbol: '$', phonePrefix: '+238', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 130 },
  { name: 'Cambodia', code: 'KH', currency: 'KHR', symbol: '៛', phonePrefix: '+855', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 5100 },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', symbol: 'Fr', phonePrefix: '+237', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Central African Republic', code: 'CF', currency: 'XAF', symbol: 'Fr', phonePrefix: '+236', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Chad', code: 'TD', currency: 'XAF', symbol: 'Fr', phonePrefix: '+235', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Chile', code: 'CL', currency: 'CLP', symbol: '$', phonePrefix: '+56', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1100 },
  { name: 'China', code: 'CN', currency: 'CNY', symbol: '¥', phonePrefix: '+86', phoneLength: 11, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 9 },
  { name: 'Colombia', code: 'CO', currency: 'COP', symbol: '$', phonePrefix: '+57', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4800 },
  { name: 'Comoros', code: 'KM', currency: 'KMF', symbol: 'Fr', phonePrefix: '+269', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 550 },
  { name: 'Congo (Congo-Brazzaville)', code: 'CG', currency: 'XAF', symbol: 'Fr', phonePrefix: '+242', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Congo (Democratic Republic)', code: 'CD', currency: 'CDF', symbol: 'Fr', phonePrefix: '+243', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2500 },
  { name: 'Costa Rica', code: 'CR', currency: 'CRC', symbol: '₡', phonePrefix: '+506', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 650 },
  { name: 'Croatia', code: 'HR', currency: 'EUR', symbol: '€', phonePrefix: '+385', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Cuba', code: 'CU', currency: 'CUP', symbol: '$', phonePrefix: '+53', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 30 },
  { name: 'Cyprus', code: 'CY', currency: 'EUR', symbol: '€', phonePrefix: '+357', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Czechia (Czech Republic)', code: 'CZ', currency: 'CZK', symbol: 'Kč', phonePrefix: '+420', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 28 },
  { name: 'Denmark', code: 'DK', currency: 'DKK', symbol: 'kr', phonePrefix: '+45', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 8.5 },
  { name: 'Djibouti', code: 'DJ', currency: 'DJF', symbol: 'Fr', phonePrefix: '+253', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 220 },
  { name: 'Dominica', code: 'DM', currency: 'XCD', symbol: '$', phonePrefix: '+1-767', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Dominican Republic', code: 'DO', currency: 'DOP', symbol: 'RD$', phonePrefix: '+1-809', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 70 },
  { name: 'Ecuador', code: 'EC', currency: 'USD', symbol: '$', phonePrefix: '+593', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Egypt', code: 'EG', currency: 'EGP', symbol: '£', phonePrefix: '+20', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 60 },
  { name: 'El Salvador', code: 'SV', currency: 'USD', symbol: '$', phonePrefix: '+503', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Equatorial Guinea', code: 'GQ', currency: 'XAF', symbol: 'Fr', phonePrefix: '+240', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Eritrea', code: 'ER', currency: 'ERN', symbol: 'Nfk', phonePrefix: '+291', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 19 },
  { name: 'Estonia', code: 'EE', currency: 'EUR', symbol: '€', phonePrefix: '+372', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Eswatini', code: 'SZ', currency: 'SZL', symbol: 'L', phonePrefix: '+268', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 23 },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', symbol: 'Br', phonePrefix: '+251', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 70 },
  { name: 'Fiji', code: 'FJ', currency: 'FJD', symbol: '$', phonePrefix: '+679', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.8 },
  { name: 'Finland', code: 'FI', currency: 'EUR', symbol: '€', phonePrefix: '+358', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'France', code: 'FR', currency: 'EUR', symbol: '€', phonePrefix: '+33', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Gabon', code: 'GA', currency: 'XAF', symbol: 'Fr', phonePrefix: '+241', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Gambia', code: 'GM', currency: 'GMD', symbol: 'D', phonePrefix: '+220', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 80 },
  { name: 'Georgia', code: 'GE', currency: 'GEL', symbol: '₾', phonePrefix: '+995', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.3 },
  { name: 'Ghana', code: 'GH', currency: 'GHS', symbol: 'GH₵', phonePrefix: '+233', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 15 },
  { name: 'Greece', code: 'GR', currency: 'EUR', symbol: '€', phonePrefix: '+30', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Grenada', code: 'GD', currency: 'XCD', symbol: '$', phonePrefix: '+1-473', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Guatemala', code: 'GT', currency: 'GTQ', symbol: 'Q', phonePrefix: '+502', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 9.8 },
  { name: 'Guinea', code: 'GN', currency: 'GNF', symbol: 'Fr', phonePrefix: '+224', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 10000 },
  { name: 'Guinea-Bissau', code: 'GW', currency: 'XOF', symbol: 'Fr', phonePrefix: '+245', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Guyana', code: 'GY', currency: 'GYD', symbol: '$', phonePrefix: '+592', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 260 },
  { name: 'Haiti', code: 'HT', currency: 'HTG', symbol: 'G', phonePrefix: '+509', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 160 },
  { name: 'Holy See', code: 'VA', currency: 'EUR', symbol: '€', phonePrefix: '+379', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Honduras', code: 'HN', currency: 'HNL', symbol: 'L', phonePrefix: '+504', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 31 },
  { name: 'Hungary', code: 'HU', currency: 'HUF', symbol: 'Ft', phonePrefix: '+36', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 450 },
  { name: 'Iceland', code: 'IS', currency: 'ISK', symbol: 'kr', phonePrefix: '+354', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 170 },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', symbol: 'Rp', phonePrefix: '+62', phoneLength: 11, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 20000 },
  { name: 'Iran', code: 'IR', currency: 'IRR', symbol: '﷼', phonePrefix: '+98', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 50000 },
  { name: 'Iraq', code: 'IQ', currency: 'IQD', symbol: 'ع.د', phonePrefix: '+964', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1600 },
  { name: 'Ireland', code: 'IE', currency: 'EUR', symbol: '€', phonePrefix: '+353', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Israel', code: 'IL', currency: 'ILS', symbol: '₪', phonePrefix: '+972', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.6 },
  { name: 'Italy', code: 'IT', currency: 'EUR', symbol: '€', phonePrefix: '+39', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Jamaica', code: 'JM', currency: 'JMD', symbol: '$', phonePrefix: '+1-876', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 190 },
  { name: 'Japan', code: 'JP', currency: 'JPY', symbol: '¥', phonePrefix: '+81', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 180 },
  { name: 'Jordan', code: 'JO', currency: 'JOD', symbol: 'د.ا', phonePrefix: '+962', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 0.89 },
  { name: 'Kazakhstan', code: 'KZ', currency: 'KZT', symbol: '₸', phonePrefix: '+7', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 560 },
  { name: 'Kenya', code: 'KE', currency: 'KES', symbol: 'KSh', phonePrefix: '+254', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 180 },
  { name: 'Kiribati', code: 'KI', currency: 'AUD', symbol: '$', phonePrefix: '+686', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.91 },
  { name: 'Kuwait', code: 'KW', currency: 'KWD', symbol: 'د.ك', phonePrefix: '+965', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 0.39 },
  { name: 'Kyrgyzstan', code: 'KG', currency: 'KGS', symbol: 'с', phonePrefix: '+996', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 110 },
  { name: 'Laos', code: 'LA', currency: 'LAK', symbol: '₭', phonePrefix: '+856', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 25000 },
  { name: 'Latvia', code: 'LV', currency: 'EUR', symbol: '€', phonePrefix: '+371', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Lebanon', code: 'LB', currency: 'LBP', symbol: 'ل.ل', phonePrefix: '+961', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 100000 },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', symbol: 'L', phonePrefix: '+266', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 23 },
  { name: 'Liberia', code: 'LR', currency: 'LRD', symbol: '$', phonePrefix: '+231', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 240 },
  { name: 'Libya', code: 'LY', currency: 'LYD', symbol: 'ل.د', phonePrefix: '+218', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 6 },
  { name: 'Liechtenstein', code: 'LI', currency: 'CHF', symbol: 'Fr', phonePrefix: '+423', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.1 },
  { name: 'Lithuania', code: 'LT', currency: 'EUR', symbol: '€', phonePrefix: '+370', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Luxembourg', code: 'LU', currency: 'EUR', symbol: '€', phonePrefix: '+352', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', symbol: 'Ar', phonePrefix: '+261', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 5600 },
  { name: 'Malawi', code: 'MW', currency: 'MWK', symbol: 'MK', phonePrefix: '+265', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2100 },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', symbol: 'RM', phonePrefix: '+60', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 6 },
  { name: 'Maldives', code: 'MV', currency: 'MVR', symbol: '.ރ', phonePrefix: '+960', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 19 },
  { name: 'Mali', code: 'ML', currency: 'XOF', symbol: 'Fr', phonePrefix: '+223', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Malta', code: 'MT', currency: 'EUR', symbol: '€', phonePrefix: '+356', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Marshall Islands', code: 'MH', currency: 'USD', symbol: '$', phonePrefix: '+692', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', symbol: 'UM', phonePrefix: '+222', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 49 },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', symbol: '₨', phonePrefix: '+230', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 58 },
  { name: 'Mexico', code: 'MX', currency: 'MXN', symbol: '$', phonePrefix: '+52', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 21 },
  { name: 'Micronesia', code: 'FM', currency: 'USD', symbol: '$', phonePrefix: '+691', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Moldova', code: 'MD', currency: 'MDL', symbol: 'L', phonePrefix: '+373', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 22 },
  { name: 'Monaco', code: 'MC', currency: 'EUR', symbol: '€', phonePrefix: '+377', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Mongolia', code: 'MN', currency: 'MNT', symbol: '₮', phonePrefix: '+976', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4300 },
  { name: 'Montenegro', code: 'ME', currency: 'EUR', symbol: '€', phonePrefix: '+382', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Morocco', code: 'MA', currency: 'MAD', symbol: 'د.م.', phonePrefix: '+212', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 12 },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', symbol: 'MT', phonePrefix: '+258', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 80 },
  { name: 'Myanmar', code: 'MM', currency: 'MMK', symbol: 'K', phonePrefix: '+95', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2600 },
  { name: 'Namibia', code: 'NA', currency: 'NAD', symbol: '$', phonePrefix: '+264', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 23 },
  { name: 'Nauru', code: 'NR', currency: 'AUD', symbol: '$', phonePrefix: '+674', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.91 },
  { name: 'Nepal', code: 'NP', currency: 'NPR', symbol: '₨', phonePrefix: '+977', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 168 },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', symbol: '€', phonePrefix: '+31', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', symbol: '$', phonePrefix: '+64', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 2.1 },
  { name: 'Nicaragua', code: 'NI', currency: 'NIO', symbol: 'C$', phonePrefix: '+505', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 46 },
  { name: 'Niger', code: 'NE', currency: 'XOF', symbol: 'Fr', phonePrefix: '+227', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', symbol: '₦', phonePrefix: '+234', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1600 },
  { name: 'North Korea', code: 'KP', currency: 'KPW', symbol: '₩', phonePrefix: '+850', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1100 },
  { name: 'North Macedonia', code: 'MK', currency: 'MKD', symbol: 'ден', phonePrefix: '+389', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 72 },
  { name: 'Norway', code: 'NO', currency: 'NOK', symbol: 'kr', phonePrefix: '+47', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 13 },
  { name: 'Oman', code: 'OM', currency: 'OMR', symbol: 'ر.ع.', phonePrefix: '+968', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 0.48 },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', symbol: '₨', phonePrefix: '+92', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 350 },
  { name: 'Palau', code: 'PW', currency: 'USD', symbol: '$', phonePrefix: '+680', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Palestine State', code: 'PS', currency: 'ILS', symbol: '₪', phonePrefix: '+970', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.6 },
  { name: 'Panama', code: 'PA', currency: 'PAB', symbol: 'B/.', phonePrefix: '+507', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Papua New Guinea', code: 'PG', currency: 'PGK', symbol: 'K', phonePrefix: '+675', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.8 },
  { name: 'Paraguay', code: 'PY', currency: 'PYG', symbol: '₲', phonePrefix: '+595', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 9200 },
  { name: 'Peru', code: 'PE', currency: 'PEN', symbol: 'S/.', phonePrefix: '+51', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.7 },
  { name: 'Philippines', code: 'PH', currency: 'PHP', symbol: '₱', phonePrefix: '+63', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 71 },
  { name: 'Poland', code: 'PL', currency: 'PLN', symbol: 'zł', phonePrefix: '+48', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 5 },
  { name: 'Portugal', code: 'PT', currency: 'EUR', symbol: '€', phonePrefix: '+351', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Qatar', code: 'QA', currency: 'QAR', symbol: 'ر.ق', phonePrefix: '+974', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.6 },
  { name: 'Romania', code: 'RO', currency: 'RON', symbol: 'lei', phonePrefix: '+40', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 5.8 },
  { name: 'Russia', code: 'RU', currency: 'RUB', symbol: '₽', phonePrefix: '+7', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 115 },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', symbol: 'Fr', phonePrefix: '+250', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1600 },
  { name: 'Saint Kitts and Nevis', code: 'KN', currency: 'XCD', symbol: '$', phonePrefix: '+1-869', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Saint Lucia', code: 'LC', currency: 'XCD', symbol: '$', phonePrefix: '+1-758', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', currency: 'XCD', symbol: '$', phonePrefix: '+1-784', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.4 },
  { name: 'Samoa', code: 'WS', currency: 'WST', symbol: 'T', phonePrefix: '+685', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.5 },
  { name: 'San Marino', code: 'SM', currency: 'EUR', symbol: '€', phonePrefix: '+378', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Sao Tome and Principe', code: 'ST', currency: 'STN', symbol: 'Db', phonePrefix: '+239', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 29 },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', symbol: 'ر.س', phonePrefix: '+966', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.7 },
  { name: 'Senegal', code: 'SN', currency: 'XOF', symbol: 'Fr', phonePrefix: '+221', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Serbia', code: 'RS', currency: 'RSD', symbol: 'дин.', phonePrefix: '+381', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 138 },
  { name: 'Seychelles', code: 'SC', currency: 'SCR', symbol: '₨', phonePrefix: '+248', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 17 },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', symbol: 'Le', phonePrefix: '+232', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 28000 },
  { name: 'Singapore', code: 'SG', currency: 'SGD', symbol: '$', phonePrefix: '+65', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.7 },
  { name: 'Slovakia', code: 'SK', currency: 'EUR', symbol: '€', phonePrefix: '+421', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Slovenia', code: 'SI', currency: 'EUR', symbol: '€', phonePrefix: '+386', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Solomon Islands', code: 'SB', currency: 'SBD', symbol: '$', phonePrefix: '+677', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 11 },
  { name: 'Somalia', code: 'SO', currency: 'SOS', symbol: 'Sh', phonePrefix: '+252', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 720 },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', symbol: 'R', phonePrefix: '+27', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 23 },
  { name: 'South Korea', code: 'KR', currency: 'KRW', symbol: '₩', phonePrefix: '+82', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1700 },
  { name: 'South Sudan', code: 'SS', currency: 'SSP', symbol: '£', phonePrefix: '+211', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1300 },
  { name: 'Spain', code: 'ES', currency: 'EUR', symbol: '€', phonePrefix: '+34', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.18 },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', symbol: 'Rs', phonePrefix: '+94', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 380 },
  { name: 'Sudan', code: 'SD', currency: 'SDG', symbol: '£', phonePrefix: '+249', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Suriname', code: 'SR', currency: 'SRD', symbol: '$', phonePrefix: '+597', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 48 },
  { name: 'Sweden', code: 'SE', currency: 'SEK', symbol: 'kr', phonePrefix: '+46', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 13 },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', symbol: 'Fr', phonePrefix: '+41', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.1 },
  { name: 'Syria', code: 'SY', currency: 'SYP', symbol: '£', phonePrefix: '+963', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 16000 },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', symbol: 'NT$', phonePrefix: '+886', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 40 },
  { name: 'Tajikistan', code: 'TJ', currency: 'TJS', symbol: 'ЅМ', phonePrefix: '+992', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 14 },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', symbol: 'Sh', phonePrefix: '+255', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3200 },
  { name: 'Thailand', code: 'TH', currency: 'THB', symbol: '฿', phonePrefix: '+66', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 45 },
  { name: 'Timor-Leste', code: 'TL', currency: 'USD', symbol: '$', phonePrefix: '+670', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.26 },
  { name: 'Togo', code: 'TG', currency: 'XOF', symbol: 'Fr', phonePrefix: '+228', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 750 },
  { name: 'Tonga', code: 'TO', currency: 'TOP', symbol: 'T$', phonePrefix: '+676', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3 },
  { name: 'Trinidad and Tobago', code: 'TT', currency: 'TTD', symbol: '$', phonePrefix: '+1-868', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 8.5 },
  { name: 'Tunisia', code: 'TN', currency: 'TND', symbol: 'د.ت', phonePrefix: '+216', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 3.9 },
  { name: 'Turkey', code: 'TR', currency: 'TRY', symbol: '₺', phonePrefix: '+90', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 40 },
  { name: 'Turkmenistan', code: 'TM', currency: 'TMT', symbol: 'm', phonePrefix: '+993', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4.4 },
  { name: 'Tuvalu', code: 'TV', currency: 'AUD', symbol: '$', phonePrefix: '+688', phoneLength: 5, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 1.91 },
  { name: 'Uganda', code: 'UG', currency: 'UGX', symbol: 'Sh', phonePrefix: '+256', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 4700 },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', symbol: '₴', phonePrefix: '+380', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 50 },
  { name: 'Uruguay', code: 'UY', currency: 'UYU', symbol: '$', phonePrefix: '+598', phoneLength: 8, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 49 },
  { name: 'Uzbekistan', code: 'UZ', currency: 'UZS', symbol: 'soʻm', phonePrefix: '+998', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 15800 },
  { name: 'Vanuatu', code: 'VU', currency: 'VUV', symbol: 'Vt', phonePrefix: '+678', phoneLength: 7, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 150 },
  { name: 'Venezuela', code: 'VE', currency: 'VES', symbol: 'Bs.S', phonePrefix: '+58', phoneLength: 10, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 45 },
  { name: 'Vietnam', code: 'VN', currency: 'VND', symbol: '₫', phonePrefix: '+84', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 31000 },
  { name: 'Yemen', code: 'YE', currency: 'YER', symbol: '﷼', phonePrefix: '+967', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 315 },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', symbol: 'ZK', phonePrefix: '+260', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 31 },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', symbol: '$', phonePrefix: '+263', phoneLength: 9, postcodeRegex: /^.*$/, shippingFee: 5, conversionRate: 100 },
];

export const CATEGORIES = [
  'All',
  'Fashion',
  'Electronics',
  'Home Essentials',
  'Beauty',
  'Grocery'
];

export const BANNERS: Banner[] = [
  {
    id: '1',
    image: 'https://res.cloudinary.com/dsamz0zji/image/upload/v1767992674/Aesthetic_Fashion_Brand_Website_Advertising_Header_Popups_5_dbyy0o.png',
    title: 'Aesthetic Fashion',
    subtitle: 'Signature Series'
  },
  {
    id: '2',
    image: 'https://res.cloudinary.com/dsamz0zji/image/upload/v1768016221/Untitled_design_18_bxszio.png',
    title: 'Modern Luxury',
    subtitle: 'New Season Arrivals'
  }
];

export const PRODUCTS: Product[] = [];